[candidates.java-current]
kind = "java"
exec = ["{java}", "-Xmx4g", "-jar", "binaries/freerouting-current-executable.jar"]
sha_file = "binaries/freerouting-current.sha"
version = "current"

[candidates.rs-main]
kind = "rust"
exec = ["../target/release/freerouting"]
sha_from = ".."
