#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Keyword {
    Absolute,
    Active,
    AgainstPreferredDirectionTraceCosts,
    Attach,
    Autoroute,
    AutorouteSettings,
    Back,
    Boundary,
    Circle,
    Circuit,
    Class,
    Classes,
    ClassClass,
    Clearance,
    ClearanceClass,
    ComponentScope,
    Constant,
    Control,
    Fanout,
    Fix,
    FlipStyle,
    FortyfiveDegree,
    Fromto,
    Front,
    Horizontal,
    HostCad,
    HostVersion,
    Image,
    Jumper,
    Keepout,
    Layer,
    LayerRule,
    Length,
    LibraryScope,
    LockType,
    LogicalPart,
    LogicalPartMapping,
    Net,
    NetworkOut,
    NetworkScope,
    NinetyDegree,
    None,
    Normal,
    Off,
    On,
    Order,
    Outline,
    Padstack,
    ParserScope,
    PartLibraryScope,
    PcbScope,
    Pin,
    Pins,
    Place,
    PlacementScope,
    PlaceControl,
    PlaceKeepout,
    PlaneScope,
    PlaneViaCosts,
    Polygon,
    PolygonPath,
    PolylinePath,
    Position,
    Postroute,
    Power,
    PreferredDirection,
    PreferredDirectionTraceCosts,
    PullTight,
    Rectangle,
    ResolutionScope,
    Rotate,
    RotateFirst,
    Routes,
    Rule,
    Rules,
    Session,
    Shape,
    ShoveFixed,
    Side,
    Signal,
    SnapAngle,
    Spare,
    StartPassNo,
    StartRipupCosts,
    StringQuote,
    StructureScope,
    Type,
    UseLayer,
    UseNet,
    UseVia,
    Vertical,
    Via,
    Vias,
    ViaAtSmd,
    ViaCosts,
    ViaKeepout,
    ViaRule,
    Width,
    Window,
    Wire,
    WiringScope,
    WriteResolution,
}

impl Keyword {
    #[must_use]
    pub fn name(self) -> &'static str {
        match self {
            Keyword::Absolute => "absolute",
            Keyword::Active => "active",
            Keyword::AgainstPreferredDirectionTraceCosts => {
                "against_preferred_direction_trace_costs"
            }
            Keyword::Attach => "attach",
            Keyword::Autoroute => "autoroute",
            Keyword::AutorouteSettings => "autoroute_settings",
            Keyword::Back => "back",
            Keyword::Boundary => "boundary",
            Keyword::Circle => "circle",
            Keyword::Circuit => "circuit",
            Keyword::Class => "class",
            Keyword::Classes => "classes",
            Keyword::ClassClass => "class_class",
            Keyword::Clearance => "clearance",
            Keyword::ClearanceClass => "clearance_class",
            Keyword::ComponentScope => "component",
            Keyword::Constant => "constant",
            Keyword::Control => "control",
            Keyword::Fanout => "fanout",
            Keyword::Fix => "fix",
            Keyword::FlipStyle => "flip_style",
            Keyword::FortyfiveDegree => "fortyfive_degree",
            Keyword::Fromto => "fromto",
            Keyword::Front => "front",
            Keyword::Horizontal => "horizontal",
            Keyword::HostCad => "host_cad",
            Keyword::HostVersion => "host_version",
            Keyword::Image => "image",
            Keyword::Jumper => "jumper",
            Keyword::Keepout => "keepout",
            Keyword::Layer => "layer",
            Keyword::LayerRule => "layer_rule",
            Keyword::Length => "length",
            Keyword::LibraryScope => "library",
            Keyword::LockType => "lock_type",
            Keyword::LogicalPart => "logical_part",
            Keyword::LogicalPartMapping => "logical_part_mapping",
            Keyword::Net => "net",
            Keyword::NetworkOut => "network_out",
            Keyword::NetworkScope => "network",
            Keyword::NinetyDegree => "ninety_degree",
            Keyword::None => "none",
            Keyword::Normal => "normal",
            Keyword::Off => "off",
            Keyword::On => "on",
            Keyword::Order => "order",
            Keyword::Outline => "outline",
            Keyword::Padstack => "padstack",
            Keyword::ParserScope => "parser",
            Keyword::PartLibraryScope => "part_library",
            Keyword::PcbScope => "pcb",
            Keyword::Pin => "pin",
            Keyword::Pins => "pins",
            Keyword::Place => "place",
            Keyword::PlacementScope => "placement",
            Keyword::PlaceControl => "place_control",
            Keyword::PlaceKeepout => "place_keepout",
            Keyword::PlaneScope => "plane",
            Keyword::PlaneViaCosts => "plane_via_costs",
            Keyword::Polygon => "polygon",
            Keyword::PolygonPath => "polygon_path",
            Keyword::PolylinePath => "polyline_path",
            Keyword::Position => "position",
            Keyword::Postroute => "postroute",
            Keyword::Power => "power",
            Keyword::PreferredDirection => "preferred_direction",
            Keyword::PreferredDirectionTraceCosts => "preferred_direction_trace_costs",
            Keyword::PullTight => "pull_tight",
            Keyword::Rectangle => "rectangle",
            Keyword::ResolutionScope => "resolution",
            Keyword::Rotate => "rotate",
            Keyword::RotateFirst => "rotate_first",
            Keyword::Routes => "routes",
            Keyword::Rule => "rule",
            Keyword::Rules => "rules",
            Keyword::Session => "session",
            Keyword::Shape => "shape",
            Keyword::ShoveFixed => "shove_fixed",
            Keyword::Side => "side",
            Keyword::Signal => "signal",
            Keyword::SnapAngle => "snap_angle",
            Keyword::Spare => "spare",
            Keyword::StartPassNo => "start_pass_no",
            Keyword::StartRipupCosts => "start_ripup_costs",
            Keyword::StringQuote => "string_quote",
            Keyword::StructureScope => "structure",
            Keyword::Type => "type",
            Keyword::UseLayer => "use_layer",
            Keyword::UseNet => "use_net",
            Keyword::UseVia => "use_via",
            Keyword::Vertical => "vertical",
            Keyword::Via => "via",
            Keyword::Vias => "vias",
            Keyword::ViaAtSmd => "via_at_smd",
            Keyword::ViaCosts => "via_costs",
            Keyword::ViaKeepout => "via_keepout",
            Keyword::ViaRule => "via_rule",
            Keyword::Width => "width",
            Keyword::Window => "window",
            Keyword::Wire => "wire",
            Keyword::WiringScope => "wiring",
            Keyword::WriteResolution => "write_resolution",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum ScopeKeyword {
    Component,
    Library,
    Network,
    Parser,
    PartLibrary,
    Pcb,
    PlaceControl,
    Placement,
    Plane,
    Resolution,
    Structure,
    Wiring,
}

impl ScopeKeyword {
    #[must_use]
    pub fn to_keyword(self) -> Keyword {
        match self {
            ScopeKeyword::Component => Keyword::ComponentScope,
            ScopeKeyword::Library => Keyword::LibraryScope,
            ScopeKeyword::Network => Keyword::NetworkScope,
            ScopeKeyword::Parser => Keyword::ParserScope,
            ScopeKeyword::PartLibrary => Keyword::PartLibraryScope,
            ScopeKeyword::Pcb => Keyword::PcbScope,
            ScopeKeyword::PlaceControl => Keyword::PlaceControl,
            ScopeKeyword::Placement => Keyword::PlacementScope,
            ScopeKeyword::Plane => Keyword::PlaneScope,
            ScopeKeyword::Resolution => Keyword::ResolutionScope,
            ScopeKeyword::Structure => Keyword::StructureScope,
            ScopeKeyword::Wiring => Keyword::WiringScope,
        }
    }

    #[must_use]
    pub fn name(self) -> &'static str {
        self.to_keyword().name()
    }

    #[must_use]
    pub fn from_keyword(keyword: Keyword) -> Option<ScopeKeyword> {
        match keyword {
            Keyword::ComponentScope => Some(ScopeKeyword::Component),
            Keyword::LibraryScope => Some(ScopeKeyword::Library),
            Keyword::NetworkScope => Some(ScopeKeyword::Network),
            Keyword::ParserScope => Some(ScopeKeyword::Parser),
            Keyword::PartLibraryScope => Some(ScopeKeyword::PartLibrary),
            Keyword::PcbScope => Some(ScopeKeyword::Pcb),
            Keyword::PlaceControl => Some(ScopeKeyword::PlaceControl),
            Keyword::PlacementScope => Some(ScopeKeyword::Placement),
            Keyword::PlaneScope => Some(ScopeKeyword::Plane),
            Keyword::ResolutionScope => Some(ScopeKeyword::Resolution),
            Keyword::StructureScope => Some(ScopeKeyword::Structure),
            Keyword::WiringScope => Some(ScopeKeyword::Wiring),
            _ => None,
        }
    }
}
