[package]
name = "fr-drc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fr-dsn = { path = "../fr-dsn" }
fr-board = { path = "../fr-board" }
fr-geometry = { path = "../fr-geometry" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
fr-core = { path = "../fr-core" }
parity = { path = "../../tests/parity" }
