//! Bit-parity of the DSN write path against the committed Java reference outputs
//! (`tests/reference/<stem>/roundtrip.dsn`, produced by `scripts/gen-reference.sh` from the
//! pinned freerouting 2.3.0 jar). Plan 3 ruling 9 puts these here rather than in `tests/parity`,
//! which must not depend on `fr-dsn`.
//!
//! Each case is exactly `scripts/gen-reference/RefWriter.java`'s two steps —
//! `DsnReader.readBoard` then `DsnWriter.write` — with `designName` the input file's stem with
//! `.dsn` stripped, which is what puts `(pcb "tutorial_board"` on the reference's first line.

use std::path::Path;

use fr_board::Board;
use fr_dsn::dsn_writer;
use fr_dsn::parser::scope_parameter::DsnReadOptions;
use fr_dsn::{BoardReadResult, CoordinateTransform};

/// `RefWriter.main`'s read half: the board and the transform it was built with.
fn read_fixture(path: &Path) -> (Board, CoordinateTransform) {
    let file = std::fs::File::open(path)
        .unwrap_or_else(|e| panic!("cannot open fixture {}: {e}", path.display()));
    let options = DsnReadOptions::default();
    let stem = design_name(path);
    match fr_dsn::read_board(file, None, Some(&stem), &options) {
        BoardReadResult::Success {
            board,
            coordinate_transform,
            ..
        }
        | BoardReadResult::OutlineMissing {
            board,
            coordinate_transform,
            ..
        } => (
            *board.unwrap_or_else(|| panic!("{} produced no board", path.display())),
            coordinate_transform
                .unwrap_or_else(|| panic!("{} produced no coordinate transform", path.display())),
        ),
        // fixed: T4 (#91) — a committed fixture is never truncated.
        BoardReadResult::Partial { diagnostic, .. } => panic!("truncated: {diagnostic}"),
        BoardReadResult::ParseError { location, detail } => {
            panic!("parse error at {location}: {detail}")
        }
        BoardReadResult::IoError(e) => panic!("io error: {e}"),
    }
}

/// `RefWriter.main`'s `designName`. **One copy for the whole tree**, in `parity`, because
/// `scripts/differential/rust/src/bin/refwriter.rs` — the binary that cuts these very references
/// from the port — needs the same rule and a drift between two copies would move every family-G
/// golden with nothing failing (Plan 9 Task 0 review, S5).
use parity::dsn_design_name as design_name;

fn assert_roundtrip_parity(stem: &str, relative_fixture: &str) {
    if !parity::require_java_dir() {
        return;
    }
    let reference = parity::reference(stem, "roundtrip.dsn");
    if !parity::require_reference(&reference) {
        return;
    }
    let fixture = parity::java_dir().join(relative_fixture);
    let (board, coordinate_transform) = read_fixture(&fixture);
    let mut actual: Vec<u8> = Vec::new();
    dsn_writer::write(
        &board,
        &coordinate_transform,
        &mut actual,
        &design_name(&fixture),
        false,
    )
    .expect("write must succeed into a Vec");
    let actual = String::from_utf8(actual).expect("DSN output must be valid UTF-8");
    parity::assert_text_parity(&actual, &reference);
}

#[test]
fn tutorial_board_roundtrip_matches_java() {
    assert_roundtrip_parity(
        "tutorial_board",
        "examples/tutorial_board/tutorial_board.dsn",
    );
}

#[test]
fn issue026_j2_reference_roundtrip_matches_java() {
    assert_roundtrip_parity(
        "Issue026-J2_reference",
        "fixtures/Issue026-J2_reference.dsn",
    );
}

#[test]
fn issue103_board_unrouted_roundtrip_matches_java() {
    assert_roundtrip_parity(
        "Issue103-Board-Unrouted",
        "fixtures/Issue103-Board-Unrouted.dsn",
    );
}

#[test]
fn issue143_rpi_splitter_roundtrip_matches_java() {
    assert_roundtrip_parity(
        "Issue143-rpi_splitter",
        "fixtures/Issue143-rpi_splitter.dsn",
    );
}

// ---------------------------------------------------------------------------------------------
// Plan 3 controller ruling G (Task 15): three further references, chosen because the four above
// leave six writers untested — all four have `polyline_path = 0`, wiring `(via  = 0`,
// `(type shove_fixed|fix|protect) = 0` and `(plane  = 0`.
//
//   Issue413-test         11 `polyline_path`, 4 wiring vias, 3 fixed states (8,492 B)
//   Issue110-RelayModule  22 wiring vias, 22 fixed states           (171,349 B)
//   Issue753-CPU-85_r104  3 `(plane …)`, 65 `polyline_path`         (273,049 B)
//
// Generated by `scripts/gen-reference.sh` from the same pinned 2.3.0 jar as the other four.
// ---------------------------------------------------------------------------------------------

#[test]
fn issue413_test_roundtrip_matches_java() {
    assert_roundtrip_parity("Issue413-test", "fixtures/Issue413-test.dsn");
}

#[test]
fn issue110_relay_module_roundtrip_matches_java() {
    assert_roundtrip_parity("Issue110-RelayModule", "fixtures/Issue110-RelayModule.dsn");
}

#[test]
fn issue753_cpu_85_r104_roundtrip_matches_java() {
    assert_roundtrip_parity("Issue753-CPU-85_r104", "fixtures/Issue753-CPU-85_r104.dsn");
}

// ---------------------------------------------------------------------------------------------
// Byte-exact parity
// ---------------------------------------------------------------------------------------------

/// The seven cases above go through [`parity::assert_text_parity`], which normalises CRLF,
/// trailing spaces/tabs and runs of blank lines before comparing (plan ruling 9). This one asserts
/// the stronger property the plan actually promises — the output is byte-for-byte what the pinned
/// 2.3.0 jar wrote — so a regression that hides inside that normalisation (a lost trailing space
/// on `(snap_angle `, `(circuit `, or a `polyline_path` line) still fails.
#[test]
fn every_reference_is_byte_for_byte_identical_to_java() {
    if !parity::require_java_dir() {
        return;
    }
    for (stem, relative_fixture) in [
        (
            "tutorial_board",
            "examples/tutorial_board/tutorial_board.dsn",
        ),
        (
            "Issue026-J2_reference",
            "fixtures/Issue026-J2_reference.dsn",
        ),
        (
            "Issue103-Board-Unrouted",
            "fixtures/Issue103-Board-Unrouted.dsn",
        ),
        (
            "Issue143-rpi_splitter",
            "fixtures/Issue143-rpi_splitter.dsn",
        ),
        ("Issue413-test", "fixtures/Issue413-test.dsn"),
        ("Issue110-RelayModule", "fixtures/Issue110-RelayModule.dsn"),
        ("Issue753-CPU-85_r104", "fixtures/Issue753-CPU-85_r104.dsn"),
    ] {
        let reference_path = parity::reference(stem, "roundtrip.dsn");
        if !parity::require_reference(&reference_path) {
            continue;
        }
        let fixture = parity::java_dir().join(relative_fixture);
        let (board, coordinate_transform) = read_fixture(&fixture);
        let mut actual: Vec<u8> = Vec::new();
        dsn_writer::write(&board, &coordinate_transform, &mut actual, stem, false)
            .expect("write must succeed into a Vec");
        let expected = std::fs::read(&reference_path).expect("reference must be readable");
        if actual == expected {
            continue;
        }
        let a = String::from_utf8_lossy(&actual);
        let e = String::from_utf8_lossy(&expected);
        let first_difference = a
            .lines()
            .zip(e.lines())
            .enumerate()
            .find(|(_, (la, le))| la != le)
            .map_or_else(
                || format!("no differing line; lengths {} vs {}", a.len(), e.len()),
                |(i, (la, le))| format!("line {}:\n  actual   {la:?}\n  expected {le:?}", i + 1),
            );
        panic!(
            "{stem}: not byte-identical to {}\n{first_difference}",
            reference_path.display()
        );
    }
}

// ---------------------------------------------------------------------------------------------
// Ports of `io/specctra/DsnWriterTest.java`
// ---------------------------------------------------------------------------------------------
//
// Java's `DsnTestFixtures.loadBoard` is `read_fixture` above; `Freerouting.globalSettings = new
// GlobalSettings()` in `@BeforeEach` has no counterpart here (no global state to reset).

/// `DsnWriterTest.writesValidDsnHeader` (DsnWriterTest.java:22-31).
#[test]
fn valid_header() {
    if !parity::require_java_dir() {
        return;
    }
    let fixture = parity::java_dir().join("fixtures/Issue143-rpi_splitter.dsn");
    let (board, ct) = read_fixture(&fixture);
    let mut out: Vec<u8> = Vec::new();
    dsn_writer::write(&board, &ct, &mut out, "test", false).expect("write");
    let content = String::from_utf8(out).expect("UTF-8");
    assert!(
        content.starts_with("(pcb"),
        "DSN output must start with (pcb"
    );
    assert!(
        content.contains("(structure"),
        "DSN output must contain (structure scope"
    );
}

/// `DsnWriterTest.roundtripPreservesLayerCount` (DsnWriterTest.java:33-41): the writer's own
/// output must be readable by the reader, with the same layer count.
#[test]
fn roundtrip_preserves_layer_count() {
    if !parity::require_java_dir() {
        return;
    }
    let fixture = parity::java_dir().join("fixtures/Issue143-rpi_splitter.dsn");
    let (original, ct) = read_fixture(&fixture);
    let original_layers = original.get_layer_count();
    let mut out: Vec<u8> = Vec::new();
    dsn_writer::write(&original, &ct, &mut out, "roundtrip", false).expect("write");
    let options = DsnReadOptions::default();
    let reloaded = match fr_dsn::read_board(out.as_slice(), None, Some("roundtrip"), &options) {
        BoardReadResult::Success { board, .. } | BoardReadResult::OutlineMissing { board, .. } => {
            *board.expect("re-read must produce a board")
        }
        // fixed: T4 (#91) — the writer never emits an unclosed scope.
        BoardReadResult::Partial { diagnostic, .. } => panic!("re-read truncated: {diagnostic}"),
        BoardReadResult::ParseError { location, detail } => {
            panic!("re-read failed at {location}: {detail}")
        }
        BoardReadResult::IoError(e) => panic!("re-read io error: {e}"),
    };
    assert_eq!(original_layers, reloaded.get_layer_count());
}

/// `DsnWriterTest.compatModeProducesOutput` (DsnWriterTest.java:43-50).
#[test]
fn compat_mode_produces_output() {
    if !parity::require_java_dir() {
        return;
    }
    let fixture = parity::java_dir().join("fixtures/Issue143-rpi_splitter.dsn");
    let (board, ct) = read_fixture(&fixture);
    let mut out: Vec<u8> = Vec::new();
    dsn_writer::write(&board, &ct, &mut out, "compat-test", true).expect("write");
    let content = String::from_utf8(out).expect("UTF-8");
    assert!(
        content.starts_with("(pcb"),
        "Compat-mode DSN output must start with (pcb"
    );
}

/// `DsnWriterTest.outputStreamContainsDataAfterWrite` (DsnWriterTest.java:52-59).
// renamed: outputStreamContainsDataAfterWrite -> output_is_non_empty (the task brief's name).
#[test]
fn output_is_non_empty() {
    if !parity::require_java_dir() {
        return;
    }
    let fixture = parity::java_dir().join("fixtures/Issue143-rpi_splitter.dsn");
    let (board, ct) = read_fixture(&fixture);
    let mut out: Vec<u8> = Vec::new();
    dsn_writer::write(&board, &ct, &mut out, "flush-test", false).expect("write");
    assert!(
        !out.is_empty(),
        "output must contain data after write (flush must have occurred)"
    );
}

/// Not a Java test. `Issue143-rpi_splitter.dsn` has an empty `(wiring …)` scope — so do all four
/// parity fixtures — so none of the cases above ever reaches `Wiring::write_wire_scope`, the one
/// place `compat_mode` changes the bytes (a `(path …)` built from the trace's corners instead of a
/// `(polyline_path …)` built from its lines, Wiring.java:130-143). This drives both branches on a
/// fixture that actually has traces.
#[test]
fn compat_mode_writes_paths_where_the_default_writes_polyline_paths() {
    if !parity::require_java_dir() {
        return;
    }
    let fixture = parity::java_dir().join("fixtures/Issue413-test.dsn");
    if !fixture.exists() {
        eprintln!("SKIP: {} missing", fixture.display());
        return;
    }
    let (board, ct) = read_fixture(&fixture);
    assert!(
        !board.get_traces().is_empty(),
        "fixture must have traces for this test to mean anything"
    );

    let mut default_mode: Vec<u8> = Vec::new();
    dsn_writer::write(&board, &ct, &mut default_mode, "Issue413-test", false).expect("write");
    let default_mode = String::from_utf8(default_mode).expect("UTF-8");

    let mut compat: Vec<u8> = Vec::new();
    dsn_writer::write(&board, &ct, &mut compat, "Issue413-test", true).expect("write");
    let compat = String::from_utf8(compat).expect("UTF-8");

    assert!(default_mode.contains("(polyline_path "));
    assert!(!default_mode.contains("(path "));
    assert!(compat.contains("(path "));
    assert!(!compat.contains("(polyline_path "));
    // `Parser.writeScope` is called with `reduced = false` even in compat mode
    // (DsnWriter.java:76-80) — the header is unchanged.
    assert!(compat.contains("(string_quote "));
    assert!(compat.contains("(space_in_quoted_tokens on)"));
}

// =================================================================================================
// The generator binary itself (Plan 9 Task 0 review, S5)
// =================================================================================================

/// `scripts/gen-reference.sh --from-port` cuts every committed `roundtrip.dsn` / `unrouted.ses`
/// by running `scripts/differential/rust/src/bin/refwriter.rs`. The assertions above bind the
/// **call pair** that binary makes; this one binds **the binary**, end to end, on one stem.
///
/// # Why it earns its place
///
/// From Plan 9 Task 1 on, family G is regenerated from the port, and the only thing standing
/// between a bug in that ~40-line driver and a silent move of every DSN/SES golden is a shell
/// script nobody runs in CI. A drift in its argv handling, its `designName`, its write order or
/// its error path would surface as an unexplained golden churn at a regeneration rather than as a
/// failing test. This runs it and byte-compares.
///
/// # Why one stem, and why this one
///
/// `Issue143-rpi_splitter` is the smallest board in `fixtures.txt` (5.5 kB round trip) and the
/// driver is board-independent — it reads and writes whatever the reader produced. Seven stems
/// would cost seven times as much and bind nothing further; the *seven-stem* claim is
/// `assert_roundtrip_parity` above, which this test does not duplicate.
///
/// # The build
///
/// `scripts/differential/rust` is a **separate workspace** (excluded from the root one), so
/// `CARGO_BIN_EXE_*` cannot reach it and the binary has to be built here. It has its own
/// `target/`, so this cannot deadlock against the outer cargo's lock, and it is incremental after
/// the first run. `FR_REFWRITER_BIN` skips the build for a caller that has already built it.
#[test]
fn the_refwriter_binary_reproduces_a_committed_reference() {
    if !parity::require_java_dir() {
        return;
    }
    let reference_dsn = parity::reference("Issue143-rpi_splitter", "roundtrip.dsn");
    let reference_ses = parity::reference("Issue143-rpi_splitter", "unrouted.ses");
    if !parity::require_reference(&reference_dsn) || !parity::require_reference(&reference_ses) {
        return;
    }

    let root = parity::workspace_root();
    let manifest = root.join("scripts/differential/rust/Cargo.toml");
    let binary = match std::env::var_os("FR_REFWRITER_BIN") {
        Some(path) => std::path::PathBuf::from(path),
        None => {
            let status = std::process::Command::new(env!("CARGO"))
                .args(["build", "--release", "--bin", "refwriter", "--quiet"])
                .arg("--manifest-path")
                .arg(&manifest)
                .status()
                .expect("cargo must be runnable");
            assert!(status.success(), "building refwriter failed: {status}");
            root.join("scripts/differential/rust/target/release/refwriter")
        }
    };

    let out = std::env::temp_dir().join(format!("fr-refwriter-{}", std::process::id()));
    std::fs::create_dir_all(&out).expect("scratch directory");
    let dsn = out.join("roundtrip.dsn");
    let ses = out.join("unrouted.ses");
    let input = parity::fixture("Issue143-rpi_splitter.dsn");

    let status = std::process::Command::new(&binary)
        .arg(&input)
        .arg(&dsn)
        .arg(&ses)
        .status()
        .unwrap_or_else(|e| panic!("cannot run {}: {e}", binary.display()));
    assert!(status.success(), "refwriter exited {status}");

    // **Bytes**, not `assert_text_parity`: what the generator writes is what gets committed, so a
    // whitespace-tolerant comparison here would let exactly the drift this test exists to catch
    // through.
    for (produced, committed) in [(&dsn, &reference_dsn), (&ses, &reference_ses)] {
        let actual = std::fs::read(produced).expect("the driver wrote its output");
        let expected = std::fs::read(committed).expect("the committed reference");
        assert_eq!(
            actual.len(),
            expected.len(),
            "{} is {} bytes and {} is {}",
            produced.display(),
            actual.len(),
            committed.display(),
            expected.len()
        );
        assert!(
            actual == expected,
            "{} differs from the committed {} — scripts/gen-reference.sh --from-port would move \
             this golden",
            produced.display(),
            committed.display()
        );
    }
    std::fs::remove_dir_all(&out).ok();
}
