//! `prepare_board` — the board half of `HeadlessBoardManager.applyRouterSettingsForLoadedBoard`
//! (HeadlessBoardManager.java:739-749), i.e. the two clearance overrides Java applies to every
//! board it loads before anything routes it.
//!
//! Java's method has four steps:
//!
//! ```java
//!   int boardLayerCount = this.board.getLayerCount();
//!   if (routerSettings.getLayerCount() != boardLayerCount) routerSettings.setLayerCount(boardLayerCount);  // :741-744
//!   routerSettings.applyBoardSpecificOptimizations(this.board);                                            // :745
//!   applyCopperToEdgeClearanceOverride();                                                                  // :746
//!   applyHoleClearanceOverride();                                                                          // :747
//! ```
//!
//! The **first two mutate the settings** and are already ported, as
//! `fr_settings::resolve_headless`'s tail (`crates/fr-settings/src/resolve.rs:36-37` names
//! `:741-744` and `:745` line for line). The **last two mutate the board**, and until Plan 7
//! Task 15b nothing in the port applied them — the gap the Plan 8 survey §5.7 found. This
//! function is that half, and only that half: it takes `&RouterSettings`, so it cannot do the
//! settings steps even if it wanted to, and the call order between the two halves is Java's
//! (settings first, board second) because `resolve_headless` runs at load time and this runs
//! after it.
//!
//! # Why it is not called from `fr_dsn::read_board`
//!
//! Java reaches the overrides from *inside* the load, at `applyRouterSettingsForLoadedBoard`
//! (`:746-747`). The port's reader has no settings — `fr-dsn` does not depend on `fr-settings` —
//! so the seam is here, above it, and every caller that wants Java's `-de`/`-dr` board must call
//! it. `fr_core::apply_router_settings_for_loaded_board` (Plan 8 Task 3) is that caller on the
//! load path.
//!
//! **Correction, Plan 8 Task 3.** This comment used to say Java reached the overrides at *two*
//! sites, `createBoard:342-343` and `:746-747` (survey ruling AD), and
//! `fr_board::board::clearance_override`'s module docs carried an argument that one call lands
//! the same board as Java's two, plus one measured case where it did not. The premise was never
//! true: `HeadlessBoardManager.createBoard` is unreachable from the DSN parser, whose only
//! `BoardParserCallback` is `ReadScopeParameter$MinimalBoardManager`. Measured at the pinned jar —
//! `headless_create_board_calls=0` for a real `loadFromSpecctraDsn` — in
//! `crates/fr-core/tests/data/p8t3-clearance-overrides.txt`. So this one call **is** Java's one
//! call, and there is no divergence to weigh. Quirk #253; quirk #232 rewritten.
//!
//! **Nothing in the tree called this before Task 16.** Every existing driver, probe and parity
//! test loads through `fr_dsn::read_board` directly and therefore works on the pristine board,
//! which is what their committed references encode (`scripts/differential/java/P6T1.java:173`
//! uses `DsnReader.readBoard` for exactly the same reason). Adding this function changes none
//! of them; Task 16's `batch.ses` references, generated by the real CLI, need it.

use fr_board::Board;
use fr_settings::RouterSettings;

/// Port of `HeadlessBoardManager.applyRouterSettingsForLoadedBoard`'s board half
/// (HeadlessBoardManager.java:746-747): apply the copper-to-edge clearance override and then the
/// drill-hole clearance override, in that order.
///
/// The order matters and is not cosmetic: both overrides append a clearance class when they
/// fire, and `board_edge` therefore always takes the lower index. Java's reachable call site
/// (`:746-747`) is copper-then-hole, as is the unreachable one at `:342-343`.
///
/// Each override is skipped when its setting is `None`, which is Java's
/// `routerSettings.copperToEdgeClearanceUm == null` / `holeClearanceUm == null` guard
/// (`:470-471`, `:350-351`). The headless settings ladder always fills both
/// (`DefaultSettings.java:78, :81`), so on a CLI run both fire.
///
/// Returns whether the board changed, i.e. `copper_changed || hole_changed`. Java returns
/// `void`; the flag exists so a caller can log or assert on it.
pub fn prepare_board(board: &mut Board, settings: &RouterSettings) -> bool {
    // HeadlessBoardManager.java:746.
    let copper_changed = match settings.copper_to_edge_clearance_um {
        Some(clearance_um) => board.apply_copper_to_edge_clearance_override(clearance_um),
        None => false,
    };
    // :747.
    let hole_changed = match settings.hole_clearance_um {
        Some(clearance_um) => board.apply_hole_clearance_override(clearance_um),
        None => false,
    };
    copper_changed || hole_changed
}
