[package]
name = "fr-router"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fr-board = { path = "../fr-board" }
fr-drc = { path = "../fr-drc" }
fr-geometry = { path = "../fr-geometry" }
fr-settings = { path = "../fr-settings" }
thiserror.workspace = true

[dev-dependencies]
fr-dsn = { path = "../fr-dsn" }
parity = { path = "../../tests/parity" }
